### ISSUE TITLE
Relate Paper and Dataset

### ISSUE THREAD

**Issue by chengwei0427** [DarrenWong/code_for_dynaLO#1]
Hi, @DarrenWong 

      Happy Chinese New Year.

      Nice work, and can you upload the relate paper.

      Thanks.

**Comment by DarrenWong** [comment]
Happy Chinese New Year!

Thank you for your interest in our work, you can refer to the IEEE [link](https://ieeexplore.ieee.org/document/10337805) or the GitHub copy uploaded [here](https://github.com/DarrenWong/code_for_dynaLO/blob/main/doc/IEEE%20T-IV%20LiDAR%20Dynamic%20Scene.pdf)

**Comment by chengwei0427** [comment]
Thank you very much, problem solved.

**Comment by chengwei0427** [comment]
Hi， @DarrenWong 
I'm sorry to bother you again.
Can you upload the test dataset in BaiDuYUN (for mainland users).
Thanks.

**Comment by DarrenWong** [comment]
Sure, please find the baiduYUN link below,
链接：https://pan.baidu.com/s/14pd_2TZpg1_0fALXSRIfyw 
提取码：6sq3

**Comment by chengwei0427** [comment]
Thank you very much.
